/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.3
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2019 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Clock_1.h"
#include "Pin_PERIPUMP_OUT_2_aliases.h"
#include "Pin_PERIPUMP_OUT_2.h"
#include "Pin_PERIPUMP_OUT_1_aliases.h"
#include "Pin_PERIPUMP_OUT_1.h"
#include "PWM_PERISTALTISK_1.h"
#include "PWM_PERISTALTISK_2.h"
#include "Pin_PERIPUMP_OUT_3_aliases.h"
#include "Pin_PERIPUMP_OUT_3.h"
#include "ADC_PH.h"
#include "Pin_pH_in_aliases.h"
#include "Pin_pH_in.h"
#include "SW_UART_TEST_USB.h"
#include "SW_UART_TEST_USB_PVT.h"
#include "DS18x8.h"
#include "Pin_00_aliases.h"
#include "Pin_00.h"
#include "SDA_1_aliases.h"
#include "SDA_1.h"
#include "SCL_1_aliases.h"
#include "SCL_1.h"
#include "I2C_1.h"
#include "I2C_1_PVT.h"
#include "ADC_PH_IRQ.h"
#include "ADC_PH_theACLK.h"
#include "DS18x8_ControlReg_DRV.h"
#include "DS18x8_StatusReg_BUS.h"
#include "DS18x8_TimerDelay.h"
#include "DS18x8_ControlReg_SEL.h"
#include "DS18x8_clock_delay.h"
#include "DS18x8_Trigger.h"
#include "DS18x8_isr_DataReady.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

